main: kyloka.hotfootpls.Main
name: Hotfoot
authors: [nayoshi12, zLokkiN]
version: 1.1
commands:
  hfjoin:
    description: To join the game!
  hfleave:
    description: To leave the game!
  hftest:
    description: bleh
  hfstart:
    description: starts the game!
  hfstop:
    description: stops the game!
  hfpos1:
    description: Set position for the first corner.
  hfpos2:
    description: Set position for the second corner.
  hflist:
    description: Get the list of Arena available
  hfreset:
    description: reset the arena

permissions:
  hf.start:
    description: Admin of Hotfoot
    default: op